name: Generate and Release PDF

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
  workflow_dispatch:    # Keep manual trigger option

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo add-apt-repository multiverse
        sudo apt-get update
        sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2t64 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install 

    - name: Create temp directory
      run: mkdir temp

    - name: Generate PDF
      run: node scripts/convertToPdf.js "resume.html" "temp/resume.pdf"

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create Tag
      id: create_tag
      run: |
        TAG_NAME="v$(date +'%Y.%m.%d-%H%M')"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        git tag $TAG_NAME
        git push origin $TAG_NAME
        # Create/update the 'latest' tag
        git tag -f latest
        git push -f origin latest

    - name: Upload PDF to Release
      uses: softprops/action-gh-release@v1
      with:
        files: temp/resume.pdf
        tag_name: ${{ steps.create_tag.outputs.tag_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Create Latest Release
      uses: softprops/action-gh-release@v1
      with:
        files: temp/resume.pdf
        tag_name: latest
        name: Latest Resume
        draft: false
        prerelease: false
        generate_release_notes: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: rm -rf temp